import './globals.css'

const fontFamily = 'DM Sans, sans-serif';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body style={{fontFamily}}>{children}</body>
    </html>
  )
}
